# Generated by Django 6.0.3 on 2026-06-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_allocation_subject_alter_mark_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='digital_library/'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
    ]
