# Generated by Django 6.0.3 on 2026-06-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_book_book_file_book_is_digital'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digitalbook',
            options={'ordering': ['-uploaded_at', 'title']},
        ),
        migrations.AddField(
            model_name='digitalbook',
            name='grade',
            field=models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6'), ('Grade 7', 'Grade 7'), ('Grade 8', 'Grade 8'), ('Grade 9', 'Grade 9')], default='Grade 9', max_length=20),
        ),
    ]
